---
- name: Install PHP
  apt: name=php state=present

- name: Install PHP mods
  apt: name={{ item }} state=present
  with_items:
    - libapache2-mod-php7.0

- name: Install PHP extensions
  apt: name={{ item }} state=present
  with_items:
    - php-zip
    - php-xml
    - php-mbstring
    - php-common
    - php-mysql
