---
- name: Install MySQL
  apt: name=mysql-server state=present

- name: Install Python-MySQL
  apt: name=python-mysqldb state=present

- name: Create database
  mysql_db: db=life-organizer state=present

- name: Create database user
  mysql_user:
    name=ubuntu
    password=ubuntu
    priv=*.*:ALL
    state=present
